- name: loop with playbook
  hosts: localhost
  tasks:
    - name: basic loop
      with_items:
        - 0
        - 1
        - 2
      debug:
        msg: "Loop {{ item }}"

    - name: advance loop
      with_items:
        - { num: '0', str: 'automate' }
        - { num: '1', str: 'with' }
        - { num: '2', str: 'ansible' }
      debug:
        msg: "Loop {{ item.num }}: {{ item.str }}"
