- name: install_package
  hosts: client
  vars:
    same_packages:
      - bash
      - bash-completion
      - ca-certificates
      - curl
      - git
      - openssl
    # Alpine Linux.
    apk_packages:
      - openssh-client
      - vim
    # Debian, Ubuntu.
    apt_packages: "{{ apk_packages }}"

  tasks:
    # General Linux.
    - name: install same packages
      package: name={{ item }} state=present
      with_items: "{{ same_packages }}"
      when:
        - same_packages is defined
        - ansible_pkg_mgr != "portage"

    # Alpine Linux.
    - name: install apk packages
      apk: name={{ item }} state=present
      with_items: "{{ apk_packages }}"
      when:
        - apk_packages is defined
        - ansible_pkg_mgr == "apk"

    # Debian, Ubuntu.
    - name: install apt packages
      apt: name={{ item }} state=present
      with_items: "{{ apt_packages }}"
      when:
        - apt_packages is defined
        - ansible_pkg_mgr == "apt"